server:
  port: ${SERVER_PORT:4001}
  forward-headers-strategy: native

spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}

  # Virtual Thread (Java 21+)
  threads:
    virtual:
      enabled: true

  # Max Request/File Size
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:3GB}
      max-request-size: ${MAX_REQUEST_SIZE:3GB}

  # Database
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:tuxweb2}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}

  #JPA
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        show_sql: false
        format_sql: false

  # Redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

# File Upload Path
file:
  dir: ${UPLOAD_DIR:./upload/}

# JWT
jwt:
  secret: ${JWT_SECRET:V5gkpclbEgFKLel6LPLhJvm9Pd7H56QcizuSRRYoYgLLKumgeXjJQTdFuPThzX56}
  expiration:
    access: ${JWT_ACCESS_EXPIRATION:1800000}  # 30분 (밀리초)
    refresh: ${JWT_REFRESH_EXPIRATION:604800000}  # 7일 (밀리초)

# SpringDoc
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
